name: PMD Code Scanning

on:
  push:

permissions:
  security-events: write

jobs:
  pmd-scan:
    name: PMD code analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run PMD
        uses: pmd/pmd-github-action@v2
        with:
          rulesets: "category/java/errorprone.xml,category/java/bestpractices.xml"
          analyzeModifiedFilesOnly: false
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif